refactor /overlay mounting

diff --git a/general/overlay/init b/general/overlay/init
--- a/general/overlay/init
+++ b/general/overlay/init
@@ -12,23 +12,31 @@ mount -t proc proc /proc || exit
 grep -q overlay /proc/filesystems || exit
 
 if grep -q ubifs /proc/cmdline; then
+  echo "Mount ubi0:rootfs_data to /overlay"
   mount -t ubifs ubi0:rootfs_data /overlay
-else
-  mtdblkdev=`awk -F ':' '/rootfs_data/ {print $1}' /proc/mtd | sed 's/mtd/mtdblock/'`
-  mtdchrdev=`grep 'rootfs_data' /proc/mtd | cut -d: -f1`
-  mount -t jffs2 /dev/${mtdblkdev} /overlay
-  
-  if [ $? -ne 0 ] || { dmesg | grep "jffs2.*: Magic bitmask.*not found" > /dev/null 2>&1; } then
-	echo "jffs2 health check error, format required!"
-	flash_eraseall -j /dev/${mtdchrdev}
-	echo "Done! Remounting..."
-	mount -t jffs2 /dev/${mtdblkdev} /overlay || mount -t tmpfs tmpfs /overlay || exit
-	if ! cat /proc/mounts | grep ${mtdblkdev}; then
-	  echo "--------------------------------"
-	  echo "Crash - your flash in the trash!"
-	  echo "--------------------------------"
-	fi
+elif grep -q rootfs_data /proc/mtd; then
+  mtdchrdev=$(grep 'rootfs_data' /proc/mtd | cut -d: -f1)
+  if [ -z "$mtdchrdev" ]; then
+    echo "Cannot find MTD block for rootfs_data!"
+  else
+    # mtdblkdev=$(awk -F ':' '/rootfs_data/ {print $1}' /proc/mtd | sed 's/mtd/mtdblock/')
+    mtdblkdev=${mtdchrdev/mtd/mtdblock}
+    echo "Mount /dev/${mtdblkdev} to /overlay"
+    mount -t jffs2 /dev/${mtdblkdev} /overlay
+    if [ $? -ne 0 ] || { dmesg | grep "jffs2.*: Magic bitmask.*not found" > /dev/null 2>&1; } then
+      echo "jffs2 health check error, format required!"
+      flash_eraseall -j /dev/${mtdchrdev}
+      echo "Done! Remounting..."
+      mount -t jffs2 /dev/${mtdblkdev} /overlay || mount -t tmpfs tmpfs /overlay || exit
+      if ! grep -q ${mtdblkdev} /proc/mounts; then
+        echo "--------------------------------"
+        echo "Crash - your flash in the trash!"
+        echo "--------------------------------"
+      fi
+    fi
   fi
+else
+  echo "Nothing to mount!"
 fi
 
 if grep -q overlayfs /proc/filesystems; then
